repos:
  -   repo: https://github.com/pycqa/pylint
      rev: pylint-2.6.0
      hooks:
        -   id: pylint
            args:
              - --disable=all
              - --enable=C0114,C0115,C0116,C0301