# Stage 1: Build the React app
FROM node:20-alpine AS build

WORKDIR /app

# Copy files
COPY package.json yarn.lock ./
RUN yarn install

COPY . .
COPY .env.dev .env

# Build
RUN yarn build

# Stage 2: Serve with nginx
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY spotnet_dev.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
