name: Pylint

on:
  push:
    branches: [main]
    paths:
      - '**/*.py'
  pull_request:
    branches: [main]
    paths:
      - '**/*.py'

jobs:
  shared:
    uses: ./.github/workflows/shared_workflow.yml
    with:
      python-version: "3.12"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install pylint

      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py') --disable=all --enable=C0114,C0115,C0116,C0301

