name: Run Frontend Tests

on:
  push:
    paths:
      - 'spotnet/frontend/**'
      - 'devops/**'
  pull_request:
    paths:
      - 'spotnet/frontend/**'
      - 'devops/**'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
        working-directory: ./spotnet/frontend
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Create .env file
      run: cp .env.dev .env
      working-directory: ${{env.working-directory}}

    - name: Install dependencies
      run: yarn install
      working-directory: ${{env.working-directory}}

    - name: Run tests
      run: yarn test
      working-directory: ${{env.working-directory}}